# Generated by Django 5.2.14 on 2026-05-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="location",
            field=models.TextField(blank=True, null=True),
        ),
    ]
