# Generated by Django 5.2.14 on 2026-05-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first", "0002_alter_students_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_name", models.CharField(max_length=100)),
                ("speed", models.IntegerField(default=50)),
            ],
        ),
        migrations.DeleteModel(
            name="Privacy",
        ),
    ]
